### ISSUE TITLE
Request for Guidance or Code on Converting PDB Files to LMDB Format for Fine-Tuning in Vabs-Net

### ISSUE THREAD

**Issue by Linmj-Judy** [Heisenburger2020/Vabs-Net#2]
Thank you very much for the code you provided. I downloaded the LMDB file you offered on HuggingFace, and it seems that you have directly saved the processed protein-ligand data in the LMDB file. I currently have some PDB files, and I am curious about how I can process these PDB files into the LMDB input format required for fine-tuning your algorithm. If you are willing to provide the corresponding processing code or guidance, I would be honored.

**Comment by Heisenburger2020** [comment]
ok, I uploaded a python script to process pdb, but you might want to adjust it a little bit to fit your path or configuration.
https://github.com/Heisenburger2020/Vabs-Net/blob/main/Process_PDB.py
to be more precise:
https://github.com/Heisenburger2020/Vabs-Net/blob/11db7ad5b9c10e134908f49c2632826cb28b36af/Process_PDB.py#L140

**Comment by Linmj-Judy** [comment]
Thank you very much for providing the code to convert PDB files containing DNA into lmdb files. Do you have code for converting PDB files of proteins or protein complexes into lmdb files? If you are willing to share it, I would be very grateful.

**Comment by Heisenburger2020** [comment]
Sorry, I do not have experience processing DNA data. You could try biotite
which seems to be a new and great repo.

LIN MUJIE ***@***.***> 于2024年9月15日周日 18:27写道：
